### ISSUE TITLE
Properties AsString and AsNumber destroys JSON

### ISSUE THREAD

**Issue by skrzacikus** [sysrpl/JsonTools#10]
Example 1:
`{"a":1}`
Getting value by `n.Find('a').AsString` changes value 1 to ''

Example 2:
`{"a":"b"}`
Getting value by `n.Find('a').AsNumber` changes string 'b'  to ''

JSON is useless after using above examples, because it is different from original version and I can't rely on it.
I didn't test other properties.

**Comment by sysrpl** [comment]
This is by design. If you read the official document page located here you you will note this line:

https://www.getlazarus.org/json/

Note that AsNull, AsArray, and AsObject do not have an := assignment operator. This is because the Value of each of these types is fixed. A null node is null, an array node is array, and an object node is object. These three statements have the effect of converting the node kind and resetting its value.

So the design is, if the type is changed, by way of AsTypeName methods, then the value is reset. If you wanted to keep the value whiel changing the type you could write:

SomeString := FloatToStr(Node.AsString) // or  Node.Value
